name: Run ruby app

on:
  push:
    branches:
      - main
      - develop

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup PHP
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
          sudo apt update
          sudo apt install -y php php-gd
      - name: Run
        run: |
          php ./app.php
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: run
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
